-- Implements a simple Nios II system for the DE-series board.
-- Inputs: SW7-0 are parallel port inputs to the Nios II system.
-- CLOCK_50 is the system clock.
-- KEY0 is the active-low system reset.
-- Outputs: LED7-0 are parallel port outputs from the Nios II system.
-- SDRAM ports correspond to the SDRAM signals on the DE-series board.
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY ROBOT IS
PORT (
	SW : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	KEY : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
	CLOCK_50 : IN STD_LOGIC;
	LED : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
	DRAM_CLK, DRAM_CKE : OUT STD_LOGIC;
	DRAM_ADDR : OUT STD_LOGIC_VECTOR(12 DOWNTO 0);
	DRAM_BA : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
	DRAM_CS_N, DRAM_CAS_N, DRAM_RAS_N, DRAM_WE_N : OUT STD_LOGIC;
	DRAM_DQ : INOUT STD_LOGIC_VECTOR(15 DOWNTO 0);
	DRAM_DQM : OUT STD_LOGIC_VECTOR(1 DOWNTO 0); 
	-- Motor Driver DRV8848 interface
	MTRR_P, MTRR_N : OUT STD_LOGIC;
	MTRL_P, MTRL_N : OUT STD_LOGIC;
	MTR_Sleep_n : OUT STD_LOGIC;
	MTR_Fault_n : IN STD_LOGIC;
	-- Sensor power control (A-Cute Car)
	VCC3P3_PWRON_n : OUT STD_LOGIC;
	IR_LED_ON : OUT STD_LOGIC;
	-- ADC LTC2308 interface
	LTC_ADC_CONVST : OUT STD_LOGIC;
	LTC_ADC_SCK : OUT STD_LOGIC;
	LTC_ADC_SDI : OUT STD_LOGIC;
	LTC_ADC_SDO : IN STD_LOGIC );
END ROBOT;

ARCHITECTURE Structure OF ROBOT IS

COMPONENT nios_system_sdram
PORT (
	clk_clk : IN STD_LOGIC;
	reset_reset_n : IN STD_LOGIC;
	sdram_clk_clk : OUT STD_LOGIC;
	--leds_export : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
	switches_export : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	sdram_wire_addr : OUT STD_LOGIC_VECTOR(12 DOWNTO 0);
	sdram_wire_ba : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
	sdram_wire_cas_n : OUT STD_LOGIC;
	sdram_wire_cke : OUT STD_LOGIC;
	sdram_wire_cs_n : OUT STD_LOGIC;
	sdram_wire_dq : INOUT STD_LOGIC_VECTOR(15 DOWNTO 0);
	sdram_wire_dqm : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
	sdram_wire_ras_n : OUT STD_LOGIC;
	sdram_wire_we_n : OUT STD_LOGIC;
	-- Ground sensors PIOs
	sensor_control_export : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
	sensor_status_export : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	sensor_data0_export : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	sensor_data1_export : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	sensor_data2_export : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	sensor_data3_export : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	sensor_data4_export : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	sensor_data5_export : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	sensor_data6_export : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	kp_export : OUT STD_LOGIC_VECTOR(11 DOWNTO 0);
	kd_export : OUT STD_LOGIC_VECTOR(11 DOWNTO 0);
	start_sl_export : OUT STD_LOGIC;
	fin_sl_export : IN STD_LOGIC;
	start_rot_export : OUT STD_LOGIC;
	dir_rot_export : OUT STD_LOGIC;
	fin_rot_export : IN STD_LOGIC;
	base_speed_export : OUT STD_LOGIC_VECTOR(11 DOWNTO 0);
	pwm_avalon_interface_0_conduit_p_r_export : OUT STD_LOGIC;
	pwm_avalon_interface_0_conduit_p_l_export : OUT STD_LOGIC;
	pwm_avalon_interface_0_conduit_n_r_export : OUT STD_LOGIC;
	pwm_avalon_interface_0_conduit_n_l_export : OUT STD_LOGIC );
END COMPONENT;

COMPONENT capteurs_sol
PORT (
	clk : IN STD_LOGIC;
	reset_n : IN STD_LOGIC;
	data_capture : IN STD_LOGIC;
	data_readyr : OUT STD_LOGIC;
	data0r : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
	data1r : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
	data2r : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
	data3r : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
	data4r : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
	data5r : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
	data6r : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
	ADC_CONVSTr : OUT STD_LOGIC;
	ADC_SCK : OUT STD_LOGIC;
	ADC_SDIr : OUT STD_LOGIC;
	ADC_SDO : IN STD_LOGIC );
END COMPONENT;

-- PWM outputs from Qsys component
signal pwm_p_r_sig : STD_LOGIC;
signal pwm_n_r_sig : STD_LOGIC;
signal pwm_p_l_sig : STD_LOGIC;
signal pwm_n_l_sig : STD_LOGIC;

-- Internal signals for ground sensors
-- sensor_control_sig is output from Nios II but not used in this version (reserved for future use)
signal sensor_status_sig : STD_LOGIC_VECTOR(7 DOWNTO 0);
signal data0_sig : STD_LOGIC_VECTOR(7 DOWNTO 0);
signal data1_sig : STD_LOGIC_VECTOR(7 DOWNTO 0);
signal data2_sig : STD_LOGIC_VECTOR(7 DOWNTO 0);
signal data3_sig : STD_LOGIC_VECTOR(7 DOWNTO 0);
signal data4_sig : STD_LOGIC_VECTOR(7 DOWNTO 0);
signal data5_sig : STD_LOGIC_VECTOR(7 DOWNTO 0);
signal data6_sig : STD_LOGIC_VECTOR(7 DOWNTO 0);
signal kp_sig : STD_LOGIC_VECTOR(11 DOWNTO 0);
signal kd_sig : STD_LOGIC_VECTOR(11 DOWNTO 0);
signal start_sl_sig : STD_LOGIC;
signal fin_sl_sig : STD_LOGIC;
signal start_rot_sig : STD_LOGIC;
signal dir_rot_sig : STD_LOGIC;
signal fin_rot_sig : STD_LOGIC;
signal base_speed_sig : STD_LOGIC_VECTOR(11 DOWNTO 0);

-- Instantiate the Nios II system entity generated by the Qsys tool.
BEGIN
NiosII: nios_system_sdram
PORT MAP (
	clk_clk => CLOCK_50,
	reset_reset_n => KEY(0),
	sdram_clk_clk => DRAM_CLK,
	--leds_export => LED,
	switches_export => SW,
	sdram_wire_addr => DRAM_ADDR,
	sdram_wire_ba => DRAM_BA,
	sdram_wire_cas_n => DRAM_CAS_N,
	sdram_wire_cke => DRAM_CKE,
	sdram_wire_cs_n => DRAM_CS_N,
	sdram_wire_dq => DRAM_DQ,
	sdram_wire_dqm => DRAM_DQM,
	sdram_wire_ras_n => DRAM_RAS_N,
	sdram_wire_we_n => DRAM_WE_N,
	-- Ground sensors - sensor_control_export not used (reserved for future expansion)
	sensor_status_export => sensor_status_sig,
	sensor_data0_export => data0_sig,
	sensor_data1_export => data1_sig,
	sensor_data2_export => data2_sig,
	sensor_data3_export => data3_sig,
	sensor_data4_export => data4_sig,
	sensor_data5_export => data5_sig,
	sensor_data6_export => data6_sig,
	kp_export => kp_sig,
	kd_export => kd_sig,
	start_sl_export => start_sl_sig,
	fin_sl_export => fin_sl_sig,
	start_rot_export => start_rot_sig,
	dir_rot_export => dir_rot_sig,
	fin_rot_export => fin_rot_sig,
	base_speed_export => base_speed_sig,
	pwm_avalon_interface_0_conduit_p_r_export => pwm_p_r_sig,
	pwm_avalon_interface_0_conduit_p_l_export => pwm_p_l_sig,
	pwm_avalon_interface_0_conduit_n_r_export => pwm_n_r_sig,
	pwm_avalon_interface_0_conduit_n_l_export => pwm_n_l_sig );

-- Tie sensor inputs low when external sensor path is not used
sensor_status_sig <= (others => '0');
data0_sig <= (others => '0');
data1_sig <= (others => '0');
data2_sig <= (others => '0');
data3_sig <= (others => '0');
data4_sig <= (others => '0');
data5_sig <= (others => '0');
data6_sig <= (others => '0');

-- Direct connection from Qsys PWM conduit to motor driver pins
MTRR_P <= pwm_p_r_sig;
MTRR_N <= pwm_n_r_sig;
MTRL_P <= pwm_p_l_sig;
MTRL_N <= pwm_n_l_sig;

LED <= (others => '0');

-- Motor driver control signals
MTR_Sleep_n <= '1'; -- Enable motor driver (active high)
-- MTR_Fault_n is monitored but not used in current implementation

-- Sensor power control (A-Cute Car)
VCC3P3_PWRON_n <= '0'; -- Enable 3.3V power for sensors (active low)
IR_LED_ON <= '1'; -- Enable IR LEDs for line sensors


END Structure;